[package]
name = "markdown"
version = "1.0.0-alpha.3"
authors = ["Titus Wormer <tituswormer@gmail.com>"]
edition = "2018"
rust-version = "1.56"
description = "CommonMark compliant markdown parser in Rust with ASTs and extensions"
homepage = "https://github.com/wooorm/markdown-rs"
repository = "https://github.com/wooorm/markdown-rs"
license = "MIT"
keywords = ["commonmark", "markdown", "parse", "render", "tokenize"]
categories = ["compilers", "encoding", "parser-implementations", "parsing", "text-processing"]
include = ["src/", "license"]

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false

[dependencies]
log = "0.4"
unicode-id = { version = "0.3", features = ["no_std"] }


[dev-dependencies]
env_logger = "0.9"
criterion = "0.4"
pretty_assertions = "1"
swc_ecma_codegen = "0.127"
swc_common = "0.29"
swc_ecma_ast = "0.94"
swc_ecma_parser = "0.122"
swc_ecma_transforms_react = "0.155"
swc_ecma_visit = "0.80"

[build-dependencies]
regex = "1"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
