name: main
on:
  - pull_request
  - push
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo clippy -- -D clippy::pedantic -D clippy::cargo -A clippy::doc_link_with_quotes -A clippy::unnecessary_wraps
      - run: cargo fmt --all -- --check
      - run: cargo test
      # - run: cargo install cargo-tarpaulin && cargo tarpaulin --out Xml
      # - uses: codecov/codecov-action@v1
      - run: cargo doc --document-private-items --no-deps --release
      - run: echo '<!doctypehtml><html lang=en><meta charset=utf8><title>Redirecting…</title><link rel=canonical href=https://wooorm.com/micromark-rs/micromark><script>location = "https://wooorm.com/micromark-rs/micromark"</script><meta http-equiv=refresh content=0;url=https://wooorm.com/micromark-rs/micromark><meta name=robots content=noindex><body><h1>Redirecting…</h1><p><a href=https://wooorm.com/micromark-rs/micromark>Click here if you are not redirected.</a>' > target/doc/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/doc
          single-commit: true
          commit-message: .
          git-config-name: Titus Wormer
          git-config-email: tituswormer@gmail.com
