name: main
on:
  - pull_request
  - push
jobs:
  beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          components: rustfmt, clippy
      - run: cargo clippy -- -W clippy::pedantic
      - run: cargo fmt --all -- --check
      - run: cargo test
      # - run: cargo install cargo-tarpaulin && cargo tarpaulin --out Xml
      # - uses: codecov/codecov-action@v1
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo clippy -- -W clippy::pedantic
      - run: cargo fmt --all -- --check
      - run: cargo test
      # - run: cargo install cargo-tarpaulin && cargo tarpaulin --out Xml
      # - uses: codecov/codecov-action@v1
      - run: cargo doc --document-private-items
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: target/doc/micromark
          single-commit: true
          commit-message: .
          git-config-name: Titus Wormer
          git-config-email: tituswormer@gmail.com
